branches:
  - "main"
repositoryUrl: "https://github.com/syradar/kroppens-hyllning"
plugins:
  "@semantic-release/commit-analyzer"
  "@semantic-release/release-notes-generator"
  "@semantic-release/github"
  "@semantic-release/npm"
  "@semantic-release/git"
